spring:
  application:
    name: dp-doctor   # 定义当前项目的应用名称
  ai:
    openai:
      api-key: sk-rnmzedekocnzyodknfcwykrjmsvyupbqbwdlkmukyptygizh
      base-url: https://api.siliconflow.cn
      chat:
        options:
          model: deepseek-ai/DeepSeek-V3

  profiles:
    active: dev

  # MyBatisPlus 的配置
  mybatis-plus:
    configuration:
      log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
    global-config:
      db-config:
        id-type: assign_id
        update-strategy: not_empty
    mapper-locations: classpath*:/mappers/*.xml